"""Add handle column to Member model with named constraint

Revision ID: a9935c5f7f60
Revises: 
Create Date: 2024-10-15 12:42:03.413245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9935c5f7f60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handle', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint('uq_member_handle', ['handle'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_constraint('uq_member_handle', type_='unique')
        batch_op.drop_column('handle')

    # ### end Alembic commands ###
